package org.blogging.platform.DataAccessors.JDBC;

import org.blogging.platform.DataAccessors.Interfaces.UserDataAccessor;
import org.blogging.platform.DataTransporters.UserDataTransporter;
import org.blogging.platform.DataAccessors.Exceptions.DataAccessException;
import org.blogging.platform.Models.User;

import java.sql.*;
import java.util.Optional;

public class JDBCUserDataAccessor extends JDBCDataAccessor implements UserDataAccessor {
    enum Queries {
        INITIALIZE("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(255) UNIQUE NOT NULL,
                password VARCHAR(255) NOT NULL,
                full_name VARCHAR(255) NOT NULL,
                email VARCHAR(255),
                gender VARCHAR(1) NOT NULL,
                created_at TIMESTAMP DEFAULT(now())
            );
            CREATE INDEX ON users(ID);
            CREATE INDEX ON users(Username);
            """),
        GET_BY_ID("SELECT * FROM users WHERE id = ?"),
        GET_BY_USERNAME("SELECT * FROM users WHERE username = ?"),
        INSERT("INSERT INTO users (username, password, full_name, email, gender) VALUES (?, ?, ?, ?, ?)");

        final String query;
        Queries(String query) { this.query = query; }
    }
    @Override
    void initialize() throws SQLException {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.executeUpdate(Queries.INITIALIZE.query);
        }
    }
    @Override
    public Optional<User> getByID(Long id) throws DataAccessException {
        try (Connection connection = dataSource.getConnection(); PreparedStatement statement = connection.prepareStatement(Queries.GET_BY_ID.query)) {
            statement.setLong(1, id);
            try (ResultSet resultSet = statement.executeQuery()) {
                return resultSet.next()?  Optional.of(User.fromResultSet(resultSet)) : Optional.empty();
            }
        } catch (SQLException e) {
            throw new DataAccessException(String.format("Error Getting User By ID: %s", id), e);
        }
    }
    @Override
    public Optional<User> getByUsername(String username) throws DataAccessException {
        try (Connection connection = dataSource.getConnection(); PreparedStatement statement = connection.prepareStatement(Queries.GET_BY_USERNAME.query)) {
            statement.setString(1, username);
            try (ResultSet resultSet = statement.executeQuery()) {
                return resultSet.next()? Optional.of(User.fromResultSet(resultSet)) : Optional.empty();
            }
        } catch (SQLException e) {
            throw new DataAccessException(String.format("Error Getting User By Name: %s", username), e);
        }
    }
    @Override
    public void register(UserDataTransporter transporter) throws DataAccessException {
        try (Connection connection = dataSource.getConnection(); PreparedStatement statement = connection.prepareStatement(Queries.INSERT.query)) {
            statement.setString(1, transporter.getUsername());
            statement.setString(2, transporter.getPassword());
            statement.setString(3, transporter.getFullName());
            statement.setString(4, transporter.getEmail());
            statement.setString(5, transporter.getGender());
            statement.executeUpdate();
        } catch (SQLException e) {
            throw new DataAccessException(String.format("Error Saving User: %s", transporter.getUsername()), e);
        }
    }
}
