package org.blogging.platform.DataAccessors.JDBC;

import org.blogging.platform.DataAccessors.Interfaces.PostDataAccessor;
import org.blogging.platform.DataTransporters.PostDataTransporter;
import org.blogging.platform.DataAccessors.Exceptions.DataAccessException;
import org.blogging.platform.Models.Post;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class JDBCPostDataAccessor extends JDBCDataAccessor implements PostDataAccessor {
    enum Queries {
        INITIALIZE("""
            CREATE TABLE IF NOT EXISTS posts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL REFERENCES users(id),
                title VARCHAR NOT NULL,
                body TEXT NOT NULL,
                is_draft BOOLEAN DEFAULT(false),
                created_at TIMESTAMP DEFAULT(now())
            );
            CREATE INDEX ON posts(title);
            CREATE INDEX ON posts(user_id);
            """),
        GET_BY_ID("SELECT posts.id, user_id, username, title, body, posts.created_at, is_draft FROM posts JOIN users ON posts.user_id = users.id WHERE id = ?"),
        GET_BY_TITLE("SELECT posts.id, user_id, username, title, body, posts.created_at, is_draft FROM posts JOIN users ON posts.user_id = users.id WHERE title = ?"),
        GET_ALL("SELECT posts.id, user_id, username, title, body, posts.created_at, is_draft FROM posts JOIN users ON posts.user_id = users.id"),
        GET_LATEST("SELECT * FROM posts ORDER BY created_at DESC, id DESC LIMIT 1"),
        INSERT("INSERT INTO posts (user_id, title, body, is_draft) VALUES (?, ?, ?, ?) RETURNING id"),
        UPDATE("UPDATE posts SET title = ?, body = ?, is_draft = ? WHERE id = ?"),
        DELETE("DELETE FROM posts WHERE id = ?");

        final String query;
        Queries(String query) { this.query = query; }
    }
    @Override
    void initialize() throws SQLException {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.executeUpdate(Queries.INITIALIZE.query);
        }
    }
    @Override
    public Optional<Post> getByID(Long id) throws DataAccessException {
        try (Connection connection = dataSource.getConnection(); PreparedStatement statement = connection.prepareStatement(Queries.GET_BY_ID.query)) {
            statement.setLong(1, id);
            try (ResultSet resultSet = statement.executeQuery()) {
                return resultSet.next()? Optional.of(Post.fromResultSet(resultSet)) : Optional.empty();
            }
        } catch (SQLException e) {
            throw new DataAccessException(String.format("Error Getting Post By ID: %s", id), e);
        }
    }
    @Override
    public Optional<Post> getByTitle(String title) throws DataAccessException {
        try (Connection connection = dataSource.getConnection(); PreparedStatement statement = connection.prepareStatement(Queries.GET_BY_TITLE.query)) {
            statement.setString(1, title);
            try (ResultSet resultSet = statement.executeQuery()) {
                return resultSet.next()? Optional.of(Post.fromResultSet(resultSet)) : Optional.empty();
            }
        } catch (SQLException e) {
            throw new DataAccessException(String.format("Error Getting Post By Title: %s", title), e);
        }
    }
    @Override
    public List<Post> getAll() throws DataAccessException {
        try (Connection connection = dataSource.getConnection(); PreparedStatement statement = connection.prepareStatement(Queries.GET_ALL.query)) {
            try (ResultSet resultSet = statement.executeQuery()) {
                ArrayList<Post> posts = new ArrayList<>();
                while (resultSet.next()) posts.add(Post.fromResultSet(resultSet));
                return posts;
            }
        } catch (SQLException e) {
            throw new DataAccessException("Error Getting All Posts", e);
        }
    }
    @Override
    public long create(PostDataTransporter transporter) throws DataAccessException {
        try (Connection connection = dataSource.getConnection(); PreparedStatement statement = connection.prepareStatement(Queries.INSERT.query)) {
            statement.setLong(1, transporter.getUserID());
            statement.setString(2, transporter.getTitle());
            statement.setString(3, transporter.getBody());
            statement.setBoolean(4, transporter.getIsDraft());
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return resultSet.getLong("id");
                } else {
                    throw new DataAccessException(String.format("Error Inserting Post %s", transporter.getTitle()));
                }
            }
        } catch (SQLException e) {
            throw new DataAccessException(String.format("Error Saving Post By User: %s", transporter.getUserID()), e);
        }
    }
    @Override
    public void update(PostDataTransporter transporter) throws DataAccessException {
        try (Connection connection = dataSource.getConnection(); PreparedStatement statement = connection.prepareStatement(Queries.UPDATE.query)) {
            statement.setString(1, transporter.getTitle());
            statement.setString(2, transporter.getBody());
            statement.setBoolean(3, transporter.getIsDraft());
            statement.setLong(4, transporter.getID());
            statement.executeUpdate();
        } catch (SQLException e) {
            throw new DataAccessException(String.format("Error Updating Post By ID: %s", transporter.getID()), e);
        }
    }
    @Override
    public void delete(Long ID) throws DataAccessException {
        try (Connection connection = dataSource.getConnection(); PreparedStatement statement = connection.prepareStatement(Queries.DELETE.query)) {
            statement.setLong(1, ID);
            statement.executeUpdate();
        } catch (SQLException e) {
            throw new DataAccessException(String.format("Error Deleting Post By ID: %s", ID), e);
        }
    }
}
